### ISSUE TITLE
Remove allocations or provide allocation-free overrides to send and receive packets

### ISSUE THREAD

**Issue by ocoanet** [ixy-languages/ixy.cs#1]
I understand that the goal of this project is to write a driver in idiomatic C#. However, because it is a network driver with high performance expectations, I suppose that it should probably be written in idiomatic, yet performance oriented C#.

One of the key characteristic of performance oriented C# is to have a very low number of allocations. That is something that is done in coreclr and corefx. This technique is also used in many high performance applications (for example in finance) where allocations are only allowed during startup.

Would you consider trying to reduce or remove the allocations from the send and receive path?

Here is a naive example for `GetPacketBuffer`:
```cs
        public int GetPacketBuffers(PacketBuffer[] buffers)
        {
            var num = buffers.Length;
            if (_buffers.Count < num)
            {
                Log.Warning("Mempool only has {0} free buffers, requested {1}", _buffers.Count, num);
                num = (int)_buffers.Count;
            }
            for (int i = 0; i < num; i++)
                buffers[i] = _buffers.Pop();
            return num;
        }
```

I can make a PR if needed.

**Comment by emmericp** [comment]
Good point, most of our other drivers actually do this (big exception: the functional languages), but this one was already fast enough that we didn't really bother optimizing it further with such optimizations.

Happy to test a pull request on real hardware, thanks! :)

**Comment by ocoanet** [comment]
Can I target Core 2.1 to use `Span<T>`? It is not necessary but it would make code cleaner.

**Comment by emmericp** [comment]
Sure
